import { Recipe } from '../types'

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Green Power Oats Bowl',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    description: 'Creamy oats bowl with fruit and seeds for a filling, high-fibre breakfast.',
    cuisine: 'Modern Australian',
    mealType: 'breakfast',
    dietaryTags: ['vegetarian'],
    calories: 420,
    protein: 22,
    carbs: 48,
    fat: 14,
    prepTime: '15 mins',
    ingredients: [
      { name: 'Rolled oats', quantity: '1 cup', category: 'Grains' },
      { name: 'Greek yogurt', quantity: '1/2 cup', category: 'Dairy' },
      { name: 'Banana', quantity: '1', category: 'Produce' },
      { name: 'Chia seeds', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: ['Cook oats in water.', 'Top with yogurt, banana, and chia seeds.', 'Serve warm.'],
    allergies: ['dairy'],
    estimatedCost: 5.8,
    difficulty: 'easy',
    wasteReductionTip: 'Use extra banana slices in smoothies to reduce fruit waste.',
  },
  {
    id: 'r2',
    title: 'Lemon Herb Chicken Salad',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=1200&q=80',
    description: 'Lean grilled chicken served on a fresh salad with citrus herbs.',
    cuisine: 'Mediterranean',
    mealType: 'lunch',
    dietaryTags: ['high protein', 'low carb'],
    calories: 510,
    protein: 36,
    carbs: 24,
    fat: 21,
    prepTime: '25 mins',
    ingredients: [
      { name: 'Chicken breast', quantity: '180g', category: 'Meat' },
      { name: 'Lettuce mix', quantity: '2 cups', category: 'Produce' },
      { name: 'Cherry tomatoes', quantity: '1 cup', category: 'Produce' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: ['Grill chicken with lemon and herbs.', 'Assemble salad vegetables.', 'Slice chicken and serve on top.'],
    allergies: [],
    estimatedCost: 9.4,
    difficulty: 'easy',
    wasteReductionTip: 'Extra lettuce can be used in wraps for the next meal.',
  },
  {
    id: 'r3',
    title: 'Tofu Veggie Stir Fry',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
    description: 'Colourful tofu stir fry with vegetables and brown rice.',
    cuisine: 'Asian',
    mealType: 'dinner',
    dietaryTags: ['vegetarian', 'vegan'],
    calories: 470,
    protein: 28,
    carbs: 40,
    fat: 18,
    prepTime: '20 mins',
    ingredients: [
      { name: 'Firm tofu', quantity: '200g', category: 'Fridge' },
      { name: 'Mixed vegetables', quantity: '2 cups', category: 'Produce' },
      { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Brown rice', quantity: '1 cup', category: 'Grains' },
    ],
    steps: ['Pan-fry tofu until golden.', 'Stir-fry vegetables and sauce.', 'Serve with rice.'],
    allergies: ['soy'],
    estimatedCost: 7.6,
    difficulty: 'easy',
    wasteReductionTip: 'Use leftover stir-fry vegetables in fried rice the next day.',
  },
  {
    id: 'r4',
    title: 'Salmon Quinoa Plate',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
    description: 'Omega-rich salmon with quinoa and steamed greens.',
    cuisine: 'Nordic',
    mealType: 'dinner',
    dietaryTags: ['high protein'],
    calories: 560,
    protein: 39,
    carbs: 34,
    fat: 26,
    prepTime: '30 mins',
    ingredients: [
      { name: 'Salmon fillet', quantity: '180g', category: 'Seafood' },
      { name: 'Quinoa', quantity: '1 cup', category: 'Grains' },
      { name: 'Broccoli', quantity: '1 cup', category: 'Produce' },
      { name: 'Lemon', quantity: '1/2', category: 'Produce' },
    ],
    steps: ['Bake salmon with lemon.', 'Cook quinoa.', 'Steam broccoli and plate all components.'],
    allergies: ['fish'],
    estimatedCost: 11.2,
    difficulty: 'medium',
    wasteReductionTip: 'Cook extra quinoa to use in salad bowls for lunch.',
  },
  {
    id: 'r5',
    title: 'Chickpea Pumpkin Curry',
    image: 'https://images.unsplash.com/photo-1604908176997-4313776f6f44?auto=format&fit=crop&w=1200&q=80',
    description: 'Comforting curry with chickpeas and pumpkin in coconut sauce.',
    cuisine: 'Indian',
    mealType: 'dinner',
    dietaryTags: ['vegetarian', 'vegan', 'budget friendly'],
    calories: 530,
    protein: 20,
    carbs: 62,
    fat: 16,
    prepTime: '35 mins',
    ingredients: [
      { name: 'Chickpeas', quantity: '1 can', category: 'Pantry' },
      { name: 'Pumpkin', quantity: '2 cups', category: 'Produce' },
      { name: 'Coconut milk', quantity: '1 cup', category: 'Pantry' },
      { name: 'Curry paste', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: ['Saute curry paste.', 'Add pumpkin, chickpeas, and coconut milk.', 'Simmer until soft and serve.'],
    allergies: [],
    estimatedCost: 8.1,
    difficulty: 'easy',
    wasteReductionTip: 'Make a larger batch and freeze portions for busy days.',
  },
  {
    id: 'r6',
    title: 'Turkey Avocado Wrap',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=1200&q=80',
    description: 'Quick wholemeal wrap with turkey, avocado, and spinach.',
    cuisine: 'Western',
    mealType: 'lunch',
    dietaryTags: ['high protein'],
    calories: 450,
    protein: 30,
    carbs: 38,
    fat: 17,
    prepTime: '12 mins',
    ingredients: [
      { name: 'Wholemeal wrap', quantity: '1', category: 'Bakery' },
      { name: 'Turkey slices', quantity: '120g', category: 'Meat' },
      { name: 'Avocado', quantity: '1/2', category: 'Produce' },
      { name: 'Spinach', quantity: '1 cup', category: 'Produce' },
    ],
    steps: ['Warm the wrap.', 'Layer turkey, avocado, and spinach.', 'Roll and slice.'],
    allergies: ['gluten'],
    estimatedCost: 6.7,
    difficulty: 'easy',
    wasteReductionTip: 'Use leftover turkey slices in salads to prevent meat waste.',
  },
  {
    id: 'r7',
    title: 'Berry Chia Yogurt Parfait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
    description: 'Layered yogurt parfait with berries and chia for a quick breakfast.',
    cuisine: 'Modern Australian',
    mealType: 'breakfast',
    dietaryTags: ['vegetarian'],
    calories: 390,
    protein: 19,
    carbs: 44,
    fat: 12,
    prepTime: '10 mins',
    ingredients: [
      { name: 'Greek yogurt', quantity: '3/4 cup', category: 'Dairy' },
      { name: 'Mixed berries', quantity: '1 cup', category: 'Produce' },
      { name: 'Chia seeds', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Granola', quantity: '1/3 cup', category: 'Pantry' },
    ],
    steps: ['Layer yogurt, berries, and granola in a glass.', 'Sprinkle chia seeds on top and serve.'],
    allergies: ['dairy'],
    estimatedCost: 5.4,
    difficulty: 'easy',
    wasteReductionTip: 'Use soft berries in smoothies before they spoil.',
  },
  {
    id: 'r8',
    title: 'Vietnamese Lemongrass Beef Bowl',
    image: 'https://images.unsplash.com/photo-1514511547115-ccae5d1787d1?auto=format&fit=crop&w=1200&q=80',
    description: 'Aromatic lemongrass beef served with rice and fresh herbs.',
    cuisine: 'Vietnamese',
    mealType: 'dinner',
    dietaryTags: ['high protein'],
    calories: 590,
    protein: 40,
    carbs: 52,
    fat: 24,
    prepTime: '30 mins',
    ingredients: [
      { name: 'Beef strips', quantity: '180g', category: 'Meat' },
      { name: 'Lemongrass', quantity: '2 stalks', category: 'Produce' },
      { name: 'Jasmine rice', quantity: '1 cup', category: 'Grains' },
      { name: 'Cucumber', quantity: '1/2', category: 'Produce' },
    ],
    steps: ['Marinate beef with chopped lemongrass.', 'Pan-sear beef until cooked.', 'Serve over rice with cucumber.'],
    allergies: [],
    estimatedCost: 10.6,
    difficulty: 'medium',
    wasteReductionTip: 'Use leftover herbs and cucumber in a side salad.',
  },
  {
    id: 'r9',
    title: 'Mediterranean Tuna Pasta',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
    description: 'Protein-rich tuna pasta with olives, cherry tomatoes, and herbs.',
    cuisine: 'Mediterranean',
    mealType: 'lunch',
    dietaryTags: ['high protein', 'budget friendly'],
    calories: 540,
    protein: 34,
    carbs: 58,
    fat: 16,
    prepTime: '20 mins',
    ingredients: [
      { name: 'Wholemeal pasta', quantity: '120g', category: 'Grains' },
      { name: 'Tuna can', quantity: '1 can', category: 'Pantry' },
      { name: 'Cherry tomatoes', quantity: '1 cup', category: 'Produce' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: ['Cook pasta until al dente.', 'Mix tuna, tomatoes, and olive oil.', 'Combine and serve warm.'],
    allergies: ['fish', 'gluten'],
    estimatedCost: 7.9,
    difficulty: 'easy',
    wasteReductionTip: 'Leftover pasta can be packed for next-day lunch.',
  },
  {
    id: 'r10',
    title: 'Vegan Lentil Tomato Soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',
    description: 'Hearty lentil soup with tomato and vegetables for budget-friendly nutrition.',
    cuisine: 'Western',
    mealType: 'dinner',
    dietaryTags: ['vegan', 'vegetarian', 'budget friendly'],
    calories: 430,
    protein: 24,
    carbs: 49,
    fat: 10,
    prepTime: '35 mins',
    ingredients: [
      { name: 'Red lentils', quantity: '1 cup', category: 'Pantry' },
      { name: 'Tomato passata', quantity: '2 cups', category: 'Pantry' },
      { name: 'Carrot', quantity: '1', category: 'Produce' },
      { name: 'Vegetable stock', quantity: '3 cups', category: 'Pantry' },
    ],
    steps: ['Saute carrot pieces briefly.', 'Add lentils, passata, and stock.', 'Simmer until lentils are soft and blend lightly.'],
    allergies: [],
    estimatedCost: 6.2,
    difficulty: 'easy',
    wasteReductionTip: 'Freeze extra soup portions to reduce weekday cooking waste.',
  },
]
